# Generated by Django 2.1.1 on 2019-09-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('teachername', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
    ]
