# Generated by Django 2.1.5 on 2020-03-12 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studied_section', to='ecommerceweb.Student'),
        ),
    ]
