# Generated by Django 2.1.5 on 2020-01-06 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topictype',
        ),
    ]
