# Generated by Django 2.1.5 on 2020-01-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceweb', '0002_remove_topic_topictype'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topictype',
            field=models.IntegerField(choices=[(0, 'normal'), (1, 'media')], default=0),
        ),
    ]
