# Generated by Django 2.1.1 on 2019-09-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceWeb', '0005_auto_20190924_1609'),
        ('ecommerceWeb', '0004_auto_20190924_1606'),
    ]

    operations = [
    ]
