# Generated by Django 2.1.5 on 2020-01-06 23:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceweb', '0007_experiment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='experimentdeadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ecommerceweb.Student'),
        ),
    ]
