# Generated by Django 2.1.1 on 2019-09-24 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceWeb', '0008_auto_20190924_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacherid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecommerceWeb.User'),
        ),
    ]
