# Generated by Django 2.1.5 on 2019-09-26 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceWeb', '0009_auto_20190924_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapterid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=600)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationid', models.AutoField(primary_key=True, serialize=False)),
                ('read', models.BooleanField(default=False)),
                ('content', models.CharField(max_length=600)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pathlist',
            fields=[
                ('pathlistid', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(0, 'ppt'), (1, 'jpg'), (2, 'url')])),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=600)),
                ('a', models.CharField(max_length=200)),
                ('b', models.CharField(max_length=200)),
                ('c', models.CharField(max_length=200)),
                ('d', models.CharField(max_length=200)),
                ('questionType', models.IntegerField()),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sectionid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_avg', models.FloatField()),
                ('studentnum', models.IntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Section')),
            ],
        ),
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topicid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Section')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentid',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacherid',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='students',
            field=models.ManyToManyField(through='ecommerceWeb.Progress', to='ecommerceWeb.Student'),
        ),
        migrations.AddField(
            model_name='testscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Student'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Teacher'),
        ),
        migrations.AddField(
            model_name='section',
            name='teachers',
            field=models.ManyToManyField(through='ecommerceWeb.Statistic', to='ecommerceWeb.Teacher'),
        ),
        migrations.AddField(
            model_name='progress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Student'),
        ),
        migrations.AddField(
            model_name='progress',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Topic'),
        ),
        migrations.AddField(
            model_name='pathlist',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Topic'),
        ),
        migrations.AddField(
            model_name='notification',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Student'),
        ),
        migrations.AddField(
            model_name='comment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Student'),
        ),
        migrations.AddField(
            model_name='comment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Teacher'),
        ),
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='statistic',
            unique_together={('teacher', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('student', 'topic')},
        ),
    ]
