# Generated by Django 2.1.5 on 2020-01-07 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceweb', '0010_experiment_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionSimulation',
            fields=[
                ('simulationid', models.AutoField(primary_key=True, serialize=False)),
                ('simulationtype', models.IntegerField()),
                ('simulationtitle', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceweb.Section')),
            ],
        ),
        migrations.CreateModel(
            name='SectionSimulationAnswer',
            fields=[
                ('answerid', models.AutoField(primary_key=True, serialize=False)),
                ('answertitle', models.TextField()),
                ('content', models.TextField()),
                ('sectionsimulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceweb.SectionSimulation')),
            ],
        ),
    ]
