# Generated by Django 2.1.5 on 2019-09-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceweb', '0010_auto_20190926_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=45),
        ),
    ]
