# Generated by Django 2.1.5 on 2020-01-07 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceweb', '0011_sectionsimulation_sectionsimulationanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionQuestion',
            fields=[
                ('questionid', models.AutoField(primary_key=True, serialize=False)),
                ('questiontitle', models.TextField()),
                ('content', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceweb.Section')),
            ],
        ),
    ]
