# Generated by Django 2.2.6 on 2019-10-02 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceweb', '0012_auto_20191002_2001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestRecord',
        ),
    ]
