# Generated by Django 2.2.6 on 2019-10-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceWeb', '0014_testrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrecord',
            name='studentid',
        ),
        migrations.DeleteModel(
            name='QuestionRecord',
        ),
        migrations.DeleteModel(
            name='TestRecord',
        ),
    ]
