# Generated by Django 2.2.6 on 2019-10-03 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceWeb', '0015_auto_20191003_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('testid', models.AutoField(primary_key=True, serialize=False)),
                ('testname', models.CharField(max_length=200)),
                ('testtime', models.DurationField()),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('recordid', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('state', models.IntegerField()),
                ('score', models.IntegerField()),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Student')),
                ('testid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Test')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionRecord',
            fields=[
                ('recordid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('istrue', models.IntegerField()),
                ('questionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Question')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Student')),
                ('testid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Test')),
            ],
        ),
    ]
