# Generated by Django 2.2.6 on 2019-10-22 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceWeb', '0018_auto_20191022_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('testid', models.AutoField(primary_key=True, serialize=False)),
                ('testname', models.CharField(max_length=200)),
                ('testtime', models.IntegerField()),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('recordid', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('state', models.IntegerField()),
                ('score', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Test')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionRecord',
            fields=[
                ('recordid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
                ('istrue', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Test')),
            ],
        ),
    ]
