# Generated by Django 2.2.6 on 2019-10-24 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceweb', '0022_auto_20191024_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('testid', models.AutoField(primary_key=True, serialize=False)),
                ('testname', models.CharField(max_length=200)),
                ('testtime', models.IntegerField()),
                ('state', models.IntegerField()),
                ('xznum', models.IntegerField()),
                ('dxnnum', models.IntegerField()),
                ('pdnum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('recordid', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('state', models.IntegerField()),
                ('score', models.IntegerField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceweb.Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceweb.Test')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionRecord',
            fields=[
                ('recordid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200, null=True)),
                ('istrue', models.IntegerField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceweb.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceweb.Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceweb.Test')),
            ],
        ),
    ]
