# Generated by Django 2.2.6 on 2019-10-31 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceweb', '0027_questionrecord_test_testrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='testrecord',
            name='test',
        ),
        migrations.DeleteModel(
            name='QuestionRecord',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestRecord',
        ),
    ]
