# Generated by Django 2.2.6 on 2019-10-31 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceWeb', '0028_auto_20191031_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('testid', models.AutoField(primary_key=True, serialize=False)),
                ('testname', models.CharField(max_length=200)),
                ('testtime', models.IntegerField()),
                ('state', models.IntegerField()),
                ('xznum', models.IntegerField()),
                ('dxnum', models.IntegerField()),
                ('pdnum', models.IntegerField()),
                ('testscore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('recordid', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.CharField(max_length=200, null=True)),
                ('duration', models.CharField(max_length=200, null=True)),
                ('state', models.IntegerField()),
                ('score', models.IntegerField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Test')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionRecord',
            fields=[
                ('recordid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200, null=True)),
                ('istrue', models.IntegerField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceWeb.Test')),
            ],
        ),
    ]
