# Generated by Django 2.1.5 on 2019-11-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceWeb', '0030_auto_20191031_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chaptername',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
