# Generated by Django 2.1.5 on 2019-11-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceWeb', '0031_auto_20191120_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='sectionname',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='topic',
            name='topicname',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
